### ISSUE TITLE
opt :  'function' registered more than once!

### ISSUE THREAD

**Issue by sploving** [mr-ma/self-checksumming#60]
Hello all,
I met the following error:
opt: CommandLine Error: Option 'function' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

any suggestion? Thanks.

**Comment by djwessel** [comment]
Hey, do you think you can share the full command that is causing this error? Thanks!

**Comment by sploving** [comment]
Hello,
It may because  my own custom LLVM/clang version. Thank you.
